export const weatherCountries = {
  Brazil: 'Brasil',
  'South Korea': 'Coreia do Sul',
  'United States of America': 'Estados Unidos',
  'United Kingdom': 'Reino Unido',
  Germany: 'Alemanha',
  France: 'França',
  Italy: 'Itália',
  Spain: 'Espanha',
  Japan: 'Japão',
  China: 'China',
  India: 'Índia',
  Canada: 'Canadá',
  Australia: 'Austrália',
  Russia: 'Rússia',
  Mexico: 'México',
  Argentina: 'Argentina',
  'South Africa': 'África do Sul',
  Nigeria: 'Nigéria',
  Kenya: 'Quênia',
  Turkey: 'Turquia',
  Indonesia: 'Indonésia',
  'Saudi Arabia': 'Arábia Saudita',
  Iraq: 'Iraque',
  Iran: 'Irã',
  Pakistan: 'Paquistão',
  Afghanistan: 'Afeganistão',
  Bangladesh: 'Bangladesh',
  Thailand: 'Tailândia',
  Vietnam: 'Vietnã',
  Philippines: 'Filipinas',
  'New Zealand': 'Nova Zelândia',
  Sweden: 'Suécia',
  Norway: 'Noruega',
  Finland: 'Finlândia',
  Denmark: 'Dinamarca',
  Netherlands: 'Países Baixos',
  Belgium: 'Bélgica',
  Switzerland: 'Suíça',
  Portugal: 'Portugal',
  Greece: 'Grécia',
  Poland: 'Polônia',
  'Czech Republic': 'República Tcheca',
  Hungary: 'Hungria',
  Austria: 'Áustria',
  Ireland: 'Irlanda',
  Romania: 'Romênia',
  Bulgaria: 'Bulgária',
  Croatia: 'Croácia',
  Serbia: 'Sérvia',
  Slovakia: 'Eslováquia',
  Slovenia: 'Eslovênia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  Montenegro: 'Montenegro',
  'North Macedonia': 'Macedônia do Norte',
  Albania: 'Albânia',
  Kosovo: 'Kosovo',
  Ukraine: 'Ucrânia',
  Belarus: 'Bielorrússia',
  Moldova: 'Moldávia',
  Georgia: 'Geórgia',
  Armenia: 'Armênia',
  Azerbaijan: 'Azerbaijão',
  Kazakhstan: 'Cazaquistão',
  Uzbekistan: 'Uzbequistão',
  Turkmenistan: 'Turquemenistão',
  Kyrgyzstan: 'Quirguistão',
  Tajikistan: 'Tajiquistão',
  Mongolia: 'Mongólia',
  'North Korea': 'Coreia do Norte',
  Malaysia: 'Malásia',
  Singapore: 'Singapura',
  Brunei: 'Brunei',
  'Timor-Leste': 'Timor-Leste',
  'Papua New Guinea': 'Papua Nova Guiné',
  'Solomon Islands': 'Ilhas Salomão',
  Fiji: 'Fiji',
  Vanuatu: 'Vanuatu',
  Samoa: 'Samoa',
  Tonga: 'Tonga',
  Tuvalu: 'Tuvalu',
  Kiribati: 'Kiribati',
  'Marshall Islands': 'Ilhas Marshall',
  Micronesia: 'Micronésia',
  Palau: 'Palau',
  Nauru: 'Nauru',
  Comoros: 'Comores',
  Madagascar: 'Madagáscar',
  Mauritius: 'Maurício',
  Seychelles: 'Seicheles',
  Maldives: 'Maldivas',
  'Sri Lanka': 'Sri Lanka',
  Bhutan: 'Butão',
  Nepal: 'Nepal',
  Sudan: 'Sudão',
  'South Sudan': 'Sudão do Sul',
  Ethiopia: 'Etiópia',
  Somalia: 'Somália',
  Djibouti: 'Djibuti',
  Eritrea: 'Eritreia',
  Tanzania: 'Tanzânia',
  Uganda: 'Uganda',
  Rwanda: 'Ruanda',
  Burundi: 'Burundi',
  'Democratic Republic of the Congo': 'República Democrática do Congo',
  'Republic of the Congo': 'República do Congo',
  Gabon: 'Gabão',
  'Equatorial Guinea': 'Guiné Equatorial',
  'São Tomé and Príncipe': 'São Tomé e Príncipe',
  'Central African Republic': 'República Centro-Africana',
  Cameroon: 'Camarões',
  Benin: 'Benin',
  Togo: 'Togo',
  Ghana: 'Gana',
  'Ivory Coast': 'Costa do Marfim',
  Liberia: 'Libéria',
  'Sierra Leone': 'Serra Leoa',
  Guinea: 'Guiné',
  'Guinea-Bissau': 'Guiné-Bissau',
  'Cape Verde': 'Cabo Verde',
  Senegal: 'Senegal',
  Gambia: 'Gâmbia',
  Mauritania: 'Mauritânia',
  'Western Sahara': 'Saara Ocidental',
  Morocco: 'Marrocos',
  Algeria: 'Argélia',
  Tunisia: 'Tunísia',
  Libya: 'Líbia',
  Egypt: 'Egito',
  Israel: 'Israel',
  Jordan: 'Jordânia',
  Lebanon: 'Líbano',
  Syria: 'Síria',
  Cyprus: 'Chipre',
};
