export const weatherConditions = {
  Sunny: 'Ensolarado',
  Clear: 'Limpo',
  'Partly cloudy': 'Parcialmente nublado',
  Cloudy: 'Nublado',
  Overcast: 'Nublado',
  Mist: 'Nevoeiro',
  'Patchy rain possible': 'Possibilidade de chuva',
  'Patchy snow possible': 'Possibilidade de neve',
  'Patchy sleet possible': 'Possibilidade de chuva congelante',
  'Patchy freezing drizzle possible': 'Possibilidade de chuvisco congelante',
  'Thundery outbreaks possible': 'Possibilidade de surtos de tempestade',
  'Blowing snow': 'Neve levantada',
  Blizzard: 'Tempestade de neve',
  Fog: 'Nevoeiro',
  'Freezing fog': 'Nevoeiro congelante',
  'Patchy light drizzle': 'Possibilidade de chuvisco leve',
  'Light drizzle': 'Chuvisco leve',
  'Freezing drizzle': 'Chuvisco congelante',
  'Heavy freezing drizzle': 'Chuvisco congelante intenso',
  'Patchy light rain': 'Possibilidade de chuva leve',
  'Light rain': 'Chuva leve',
  'Moderate rain at times': 'Chuva moderada às vezes',
  'Moderate rain': 'Chuva moderada',
  'Heavy rain at times': 'Chuva intensa às vezes',
  'Heavy rain': 'Chuva intensa',
  'Light freezing rain': 'Chuva congelante leve',
  'Moderate or heavy freezing rain': 'Chuva congelante moderada ou intensa',
  'Light sleet': 'Chuvisco leve',
  'Moderate or heavy sleet': 'Chuvisco moderado ou intenso',
  'Patchy light snow': 'Possibilidade de neve leve',
  'Light snow': 'Neve leve',
  'Patchy moderate snow': 'Neve moderada',
  'Moderate snow': 'Neve moderada',
  'Patchy heavy snow': 'Possibilidade de neve intensa',
  'Heavy snow': 'Neve intensa',
  'Ice pellets': 'Granizo',
  'Light rain shower': 'Chuva leve',
  'Moderate or heavy rain shower': 'Chuva moderada ou intensa',
  'Torrential rain shower': 'Chuva torrencial',
  'Light sleet showers': 'Chuviscos leves',
  'Moderate or heavy sleet showers': 'Chuviscos moderados ou intensos',
  'Light snow showers': 'Neve leve',
  'Moderate or heavy snow showers': 'Neve moderada ou intensa',
  'Light showers of ice pellets': 'Chuva de granizo leve',
  'Moderate or heavy showers of ice pellets':
    'Chuva de granizo moderada ou intensa',
  'Patchy light rain with thunder': 'Possibilidade de chuva leve com trovões',
  'Moderate or heavy rain with thunder':
    'Chuva moderada ou intensa com trovões',
  'Patchy light snow with thunder': 'Possibilidade de neve leve com trovões',
  'Moderate or heavy snow with thunder': 'Neve moderada ou intensa com trovões',
};
